### ISSUE TITLE
你好大神，现在有没有将项目代码以jar包形式发布，或者是有maven依赖

### ISSUE THREAD

**Issue by newShiJ** [sunchenbin/A.CTable-Frame#3]

**Comment by sunchenbin** [comment]
有的直接依赖就可以了
<dependency>
	    <groupId>com.gitee.sunchenbin.mybatis.actable</groupId>
	    <artifactId>mybatis-enhance-actable</artifactId>
	    <version>1.0.8.1.RELEASE</version>
	</dependency>
